GET http://localhost:5000/api/applications/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWE5Mjc1ZTM2YWNlYzQ3N2NjNTZmYTEiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc3Mjg3OTgxNiwiZXhwIjoxNzczNDg0NjE2fQ.HTzbYbR8_1-X845aR4pY6tI6Qc1_RXa3GQTmn85Stv4
Content-Type: application/json


