GET http://localhost:5000/api/jobs?type=internship&location=Remote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWE5Mjc1ZTM2YWNlYzQ3N2NjNTZmYTEiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc3MzIyMDIyNCwiZXhwIjoxNzczODI1MDI0fQ.hMbkHTSUbqZhxUTgQMBmOfYFxoZH4D-EUXbnR9StvS4
Content-Type: application/json
